name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "src/**"
      - "pom.xml"
      - "mvnw"
      - "mvnw.cmd"
      - ".mvn/**"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Build
        run: ./mvnw -B clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Testes
        run: ./mvnw -B test
